server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
env:
  message: Hi im prod
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
env:
  message: Hi im test
